package ru.eremin.soap.note;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-24T00:29:03.718+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "NoteEndpointPortService",
                  wsdlLocation = "http://localhost:8080/soap/NoteService.wsdl",
                  targetNamespace = "http://eremin.ru/springboot/lessons/soap/note")
public class NoteEndpointPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eremin.ru/springboot/lessons/soap/note", "NoteEndpointPortService");
    public final static QName NoteEndpointPortSoap11 = new QName("http://eremin.ru/springboot/lessons/soap/note", "NoteEndpointPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/soap/NoteService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NoteEndpointPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/soap/NoteService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NoteEndpointPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NoteEndpointPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NoteEndpointPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NoteEndpointPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NoteEndpointPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NoteEndpointPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NoteEndpointPort
     */
    @WebEndpoint(name = "NoteEndpointPortSoap11")
    public NoteEndpointPort getNoteEndpointPortSoap11() {
        return super.getPort(NoteEndpointPortSoap11, NoteEndpointPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NoteEndpointPort
     */
    @WebEndpoint(name = "NoteEndpointPortSoap11")
    public NoteEndpointPort getNoteEndpointPortSoap11(WebServiceFeature... features) {
        return super.getPort(NoteEndpointPortSoap11, NoteEndpointPort.class, features);
    }

}
